#!/usr/bin/env python3
"""Generate the static Vulkan "loader" WoWPS links on the PS5.

RADV is linked into the app as an ICD archive: it exports only
vk_icdGetInstanceProcAddr, not the vk* prototypes the renderer, VMA and
imgui_impl_vulkan call. This writes one definition per Vulkan command that the
non-platform headers (vulkan_core.h) declare: core 1.0-1.4 plus every KHR/EXT
extension. Each resolves its driver entry point once through
vk_icdGetInstanceProcAddr, using the live instance for anything that is not a
global command. Mesa returns dispatching trampolines for device commands, so
one lookup per command serves every device.

    gen_vk_loader.py <vk.xml> <out.c>
"""
import sys
import xml.etree.ElementTree as ET

GLOBAL = {"vkCreateInstance", "vkEnumerateInstanceExtensionProperties",
          "vkEnumerateInstanceLayerProperties", "vkEnumerateInstanceVersion"}
SPECIAL = {"vkGetInstanceProcAddr", "vkCreateInstance", "vkDestroyInstance"}


def text(node):
    return "".join(node.itertext()).strip()


def for_vulkan(node):
    api = node.get("api")
    return api is None or "vulkan" in api.split(",")


def main(registry, out):
    root = ET.parse(registry).getroot()
    commands, aliases = {}, {}
    for cmd in root.find("commands"):
        if not for_vulkan(cmd):
            continue
        if cmd.get("alias"):
            aliases[cmd.get("name")] = cmd.get("alias")
            continue
        proto = cmd.find("proto")
        name = proto.find("name").text
        ret = text(proto)[: -len(name)].strip()
        params = [p for p in cmd.findall("param") if for_vulkan(p)]
        decls = [" ".join(text(p).split()) for p in params]
        names = [p.find("name").text for p in params]
        commands[name] = (ret, decls, names)

    wanted = []
    for feature in root.findall("feature"):
        if not for_vulkan(feature):
            continue
        for req in feature.findall("require"):
            wanted += [c.get("name") for c in req.findall("command")]
    for ext in root.find("extensions"):
        supported = ext.get("supported", "").split(",")
        if "vulkan" not in supported or ext.get("platform"):
            continue
        for req in ext.findall("require"):
            if not for_vulkan(req):
                continue
            wanted += [c.get("name") for c in req.findall("command")]

    seen, lines = set(), []
    for name in wanted:
        if name in seen or name in SPECIAL:
            continue
        seen.add(name)
        target = aliases.get(name, name)
        while target in aliases:
            target = aliases[target]
        ret, decls, names = commands[target]
        call = "return " if ret != "void" else ""
        lines.append(
            f"VKAPI_ATTR {ret} VKAPI_CALL {name}({', '.join(decls) or 'void'}) {{\n"
            f"    static PFN_{name} fn;\n"
            f"    if (!fn) fn = (PFN_{name})wowee_vk_resolve(\"{name}\", {int(name in GLOBAL)});\n"
            f"    {call}fn({', '.join(names)});\n"
            f"}}\n")

    with open(out, "w") as f:
        f.write(HEADER)
        f.write("\n".join(lines))
    print(f"{out}: {len(lines)} commands")


HEADER = r'''/* Generated by tools/ps5/gen_vk_loader.py from Mesa's vk.xml. Do not edit. */
#include <stdio.h>
#include <stdlib.h>
#include <vulkan/vulkan.h>

extern PFN_vkVoidFunction vk_icdGetInstanceProcAddr(VkInstance instance, const char *name);

static VkInstance wowee_vk_instance;

static PFN_vkVoidFunction wowee_vk_resolve(const char *name, int global) {
    PFN_vkVoidFunction fn = vk_icdGetInstanceProcAddr(global ? VK_NULL_HANDLE : wowee_vk_instance, name);
    if (!fn) {
        /* Calling a command the driver does not have is an application bug:
         * stop here with its name rather than jump to NULL. */
        fprintf(stderr, "[vk-loader] %s is not provided by RADV\n", name);
        abort();
    }
    return fn;
}

VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL vkGetInstanceProcAddr(VkInstance instance, const char *pName) {
    return vk_icdGetInstanceProcAddr(instance, pName);
}

VKAPI_ATTR VkResult VKAPI_CALL vkCreateInstance(const VkInstanceCreateInfo *pCreateInfo,
                                                const VkAllocationCallbacks *pAllocator,
                                                VkInstance *pInstance) {
    static PFN_vkCreateInstance fn;
    if (!fn) fn = (PFN_vkCreateInstance)wowee_vk_resolve("vkCreateInstance", 1);
    const VkResult result = fn(pCreateInfo, pAllocator, pInstance);
    if (result == VK_SUCCESS) wowee_vk_instance = *pInstance;
    return result;
}

VKAPI_ATTR void VKAPI_CALL vkDestroyInstance(VkInstance instance, const VkAllocationCallbacks *pAllocator) {
    static PFN_vkDestroyInstance fn;
    if (!fn) fn = (PFN_vkDestroyInstance)wowee_vk_resolve("vkDestroyInstance", 0);
    fn(instance, pAllocator);
    if (instance == wowee_vk_instance) wowee_vk_instance = VK_NULL_HANDLE;
}

'''

if __name__ == "__main__":
    main(*sys.argv[1:])
