// Compile the actual production Minimap::render body against mocked Vulkan
// commands. This checks recorded dynamic state and quad placement without a GPU.
#include <vulkan/vulkan.h>
#include "core/coordinates.hpp"
#include <glm/gtc/constants.hpp>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
#include <limits>

namespace {
void require(bool okay, const char* message) {
    if (!okay) { std::fprintf(stderr, "FAIL minimap: %s\n", message); std::exit(1); }
}
void closeTo(float actual, float expected, const char* message) {
    require(std::isfinite(actual) && std::abs(actual - expected) < .01f, message);
}
struct Recorded {
    VkViewport viewport{91, 43, 37, 19, .2f, .8f};
    VkRect2D scissor{{11, 17}, {23, 29}};
    unsigned viewportCalls = 0, scissorCalls = 0, pipelineCalls = 0, draws = 0;
    std::vector<unsigned char> push;
} recorded;
} // namespace

extern "C" {
VKAPI_ATTR void VKAPI_CALL vkCmdBindPipeline(VkCommandBuffer, VkPipelineBindPoint, VkPipeline) {
    ++recorded.pipelineCalls;
}
VKAPI_ATTR void VKAPI_CALL vkCmdSetViewport(VkCommandBuffer, uint32_t first, uint32_t count, const VkViewport* viewport) {
    require(first == 0 && count == 1, "sets the first complete viewport");
    recorded.viewport = *viewport; ++recorded.viewportCalls;
}
VKAPI_ATTR void VKAPI_CALL vkCmdSetScissor(VkCommandBuffer, uint32_t first, uint32_t count, const VkRect2D* scissor) {
    require(first == 0 && count == 1, "sets the first complete scissor");
    recorded.scissor = *scissor; ++recorded.scissorCalls;
}
VKAPI_ATTR void VKAPI_CALL vkCmdBindDescriptorSets(VkCommandBuffer, VkPipelineBindPoint, VkPipelineLayout,
    uint32_t, uint32_t, const VkDescriptorSet*, uint32_t, const uint32_t*) {}
VKAPI_ATTR void VKAPI_CALL vkCmdBindVertexBuffers(VkCommandBuffer, uint32_t, uint32_t, const VkBuffer*, const VkDeviceSize*) {}
VKAPI_ATTR void VKAPI_CALL vkCmdPushConstants(VkCommandBuffer, VkPipelineLayout, VkShaderStageFlags,
    uint32_t offset, uint32_t bytes, const void* value) {
    require(offset == 0, "push constants begin at zero");
    const auto* data = static_cast<const unsigned char*>(value);
    recorded.push.assign(data, data + bytes);
}
VKAPI_ATTR void VKAPI_CALL vkCmdDraw(VkCommandBuffer, uint32_t vertices, uint32_t instances,
    uint32_t firstVertex, uint32_t firstInstance) {
    require(recorded.viewportCalls == 1 && recorded.scissorCalls == 1,
            "overwrites stale viewport and scissor before drawing");
    require(vertices == 6 && instances == 1 && firstVertex == 0 && firstInstance == 0,
            "records the complete display quad");
    ++recorded.draws;
}
}

namespace wowee::rendering {
struct Camera { glm::vec3 forward{0,1,0}; glm::vec3 getForward() const { return forward; } };
struct Minimap {
    bool enabled = true, hasCachedFrame = true, haveRect_ = true;
    bool rotateWithCamera = false, squareShape = false;
    float rectX_ = 0, rectY_ = 0, rectW_ = 140, rectH_ = 140;
    float viewRadius = 400, opacity_ = 1;
    int mapSize = 200;
    VkPipeline displayPipeline = reinterpret_cast<VkPipeline>(1);
    VkPipelineLayout displayPipelineLayout = VK_NULL_HANDLE;
    VkDescriptorSet displayDescSet = VK_NULL_HANDLE;
    VkBuffer quadVB = VK_NULL_HANDLE;
    void render(VkCommandBuffer, const Camera&, const glm::vec3&, int, int,
                VkExtent2D, float = 0, bool = false);
};

// Generated by the runner from src/rendering/minimap.cpp: both the push
// constant declaration and the whole function, with no copied rendering logic.
#include "minimap_render_source.inc"
} // namespace wowee::rendering

int main() {
    using namespace wowee::rendering;
    Minimap map; Camera camera;
    const int sizes[][2] = {{1280,720}, {1920,1080}, {1024,768}, {3440,1440}, {1280,720}};
    for (const auto& size : sizes) for (const int divisor : {1, 2}) {
        const auto width = size[0], height = size[1];
        const float uiScale = height / 768.0f;
        map.rectW_ = map.rectH_ = 140 * uiScale;
        map.rectX_ = width - map.rectW_ - 16 * uiScale;
        map.rectY_ = 24 * uiScale;
        const VkExtent2D extent{static_cast<uint32_t>(width / divisor), static_cast<uint32_t>(height / divisor)};
        recorded = {};
        map.render(VK_NULL_HANDLE, camera, {0, 0, 0}, width, height, extent);
        require(recorded.draws == 1, "valid display records one draw");
        closeTo(recorded.viewport.x, 0, "viewport starts at the framebuffer left");
        closeTo(recorded.viewport.y, 0, "viewport starts at the framebuffer top");
        closeTo(recorded.viewport.width, extent.width, "viewport uses actual target width");
        closeTo(recorded.viewport.height, extent.height, "viewport uses actual target height");
        closeTo(recorded.viewport.minDepth, 0, "viewport resets minimum depth");
        closeTo(recorded.viewport.maxDepth, 1, "viewport resets maximum depth");
        require(recorded.scissor.offset.x == 0 && recorded.scissor.offset.y == 0 &&
                recorded.scissor.extent.width == extent.width && recorded.scissor.extent.height == extent.height,
                "scissor covers the actual display target");
        require(recorded.push.size() == sizeof(MinimapDisplayPush), "records complete minimap push constants");
        MinimapDisplayPush push;
        std::memcpy(&push, recorded.push.data(), sizeof(push));
        closeTo(push.rect.x * extent.width, map.rectX_ / divisor, "map x stays aligned with the authored UI rectangle");
        closeTo(push.rect.y * extent.height, map.rectY_ / divisor, "map y stays aligned with the authored UI rectangle");
        closeTo(push.rect.z * extent.width, map.rectW_ / divisor, "map width follows display scaling");
        closeTo(push.rect.w * extent.height, map.rectH_ / divisor, "map height follows display scaling");
    }
    const int invalid[][4] = {{0,720,1280,720}, {1280,0,1280,720}, {1280,720,0,720}, {1280,720,1280,0}};
    for (const auto& values : invalid) {
        recorded = {};
        map.render(VK_NULL_HANDLE, camera, {0,0,0}, values[0], values[1],
                   {static_cast<uint32_t>(values[2]), static_cast<uint32_t>(values[3])});
        require(recorded.pipelineCalls == 0 && recorded.draws == 0 && recorded.push.empty(),
                "zero window or framebuffer dimension records no draw commands");
    }
    std::puts("PASS minimap: production render resets dynamic viewport/scissor, preserves UI rect at four resolutions and half-size targets, ignores zero dimensions");
    const Minimap good=map;
    const float nan=std::numeric_limits<float>::quiet_NaN(),inf=std::numeric_limits<float>::infinity();
    const auto reject=[&](const glm::vec3& pos=glm::vec3(0),float orientation=0,bool hasOrientation=false){
        recorded={};map.render(VK_NULL_HANDLE,camera,pos,1280,720,{1280,720},orientation,hasOrientation);
        require(recorded.pipelineCalls==0 && recorded.draws==0 && recorded.push.empty(),"invalid state emits no GPU commands");
    };
    for(float bad:{nan,inf,-inf}) {
        map=good;map.rectX_=bad;reject();map=good;map.rectY_=bad;reject();
        map=good;map.rectW_=bad;reject();map=good;map.rectH_=bad;reject();
        map=good;map.viewRadius=bad;reject();map=good;map.opacity_=bad;reject();
        map=good;reject({bad,0,0});reject({0,bad,0});reject({0,0,0},bad,true);
        camera.forward={bad,1,0};reject();camera.forward={0,1,0};
    }
    map=good;map.rectW_=0;reject();map=good;map.rectH_=-1;reject();
    map=good;map.haveRect_=false;map.mapSize=0;reject();map=good;map.viewRadius=0;reject();
    map=good;reject({1e30f,0,0});
    std::puts("PASS minimap invalid data: hidden/invalid rectangles, world conversion bounds, radius, opacity and orientation skip GPU recording");
    for(float opacity:{-2.f,2.f}) {
        map=good;map.opacity_=opacity;recorded={};
        map.render(VK_NULL_HANDLE,camera,{0,0,0},1280,720,{1280,720});
        require(recorded.draws==1,"finite out-of-range opacity still draws");
        MinimapDisplayPush push;std::memcpy(&push,recorded.push.data(),sizeof(push));
        closeTo(push.opacity,opacity<0?0.f:1.f,"opacity is bounded");
    }
    std::puts("PASS minimap opacity: finite values clamped to the display range");

    // Actual production draw constants must be unchanged when tilting from
    // ground to sky. Lighting has no binding in the display shader.
    map=good; map.opacity_=1.f;
    std::vector<unsigned char> baseline;
    for(float pitch : {-1.55f,-.8f,0.f,.8f,1.55f}) {
        camera.forward={0,std::cos(pitch),std::sin(pitch)};
        recorded={};
        map.render(VK_NULL_HANDLE,camera,{100,200,30},1920,1080,{1920,1080},.7f,true);
        require(recorded.draws==1,"ground-to-sky tilt keeps minimap visible");
        if(baseline.empty()) baseline=recorded.push;
        require(recorded.push==baseline,"camera pitch leaves HUD display constants identical");
    }
    std::puts("PASS minimap camera pitch: actual render constants identical from ground to sky at fixed player position/yaw");

}
