#pragma once
#include "game/local_proc_rules.hpp"
#include "game/local_spell_amount.hpp"
#include "game/local_spell_ranks.hpp"
namespace wowee::game {
// Historical allocations are retained, but an executable proc cannot use a
// missing or unsupported direct prerequisite. This is a runtime admission
// check, not a migration or a reconstruction of the whole saved talent tree.
inline bool localPassiveProcPrerequisites(const LocalRealmPlayer& owner,const LocalWorldContent& c,
                                          const LocalSpellDefinition& talent) {
    return localTalentPrerequisitesReady(owner,c,talent);
}
// A persisted internal child never supplies a talent on its own. Its exact
// child ID must still be generated by the owner's supported current rank.
inline bool localProcChildTalentReady(const LocalRealmPlayer& p,const LocalWorldContent& c,const LocalSpellDefinition& child) {
    if(!child.procParentTalentId)return true;
    if(p.classId<1||p.classId>11||!validLocalTalents(p))return false;
    const auto allocated=std::find_if(p.talents.begin(),p.talents.end(),[&](const auto& t){return t.first==child.procParentTalentId;});
    if(allocated==p.talents.end())return false;
    const auto* parent=localTalentSpell(c,allocated->first,allocated->second);
    return parent && parent->passive && parent->unsupportedReason.empty() && validLocalProc(*parent) &&
        (parent->allowableClasses&(1u<<(p.classId-1))) && (child.allowableClasses&(1u<<(p.classId-1))) &&
        parent->proc.effect==LocalProcEffect::ApplyOwnerAura && parent->proc.spellId==child.id &&
        (localClearcastingChild(child)?parent->clearcastingProfile+2==child.clearcastingProfile:
            child.periodicHealMaxHealthPct?parent->proc.amount==child.periodicHealMaxHealthPct:
            parent->proc.amount==child.meleeHastePct) && localPassiveProcPrerequisites(p,c,*parent);
}
inline bool localEarthShield(const LocalSpellDefinition& d) {
    return d.proc.effect==LocalProcEffect::HealOwner &&
        (d.id==974||d.id==32593||d.id==32594||d.id==49283||d.id==49284);
}
// Higher ranks of talent spells cannot be purchased or cast before learning
// their root talent; the talent allocation survives ordinary rank replacement.
inline bool localProcTalentPrerequisite(const LocalRealmPlayer& p,const LocalWorldContent& c,const LocalSpellDefinition& d) {
    if(!localEarthShield(d)&&d.meleeSpecialProfile!=1)return true;
    const auto* root=c.spell(localEarthShield(d)?974:23881);if(!root||!root->talentId)return false;
    return std::any_of(p.talents.begin(),p.talents.end(),[&](const auto& t){return t.first==root->talentId&&t.second>=root->talentRank;});
}
inline uint32_t localProcPushbackReduction(const LocalRealmPlayer& p,const LocalWorldContent& c,const LocalSpellDefinition& cast) {
    if(!(cast.schoolMask&126))return 0; // Earth Shield aura 149 uses magic-school mask 126.
    uint32_t percent=0;
    for(const auto& aura:p.statAuras) {
        const auto* d=c.spell(aura.spellId);
        if(!aura.remainingMs||aura.mapId!=p.mapId||aura.instanceId!=p.instanceId||!d||
           !d->unsupportedReason.empty()||!validLocalProc(*d)||(d->proc.charges&&!aura.procCharges))continue;
        percent=std::max(percent,uint32_t(d->proc.pushbackPercent));
    }
    return percent;
}
inline uint32_t localProcAmountAtApplication(const LocalRealmPlayer& caster,const LocalWorldContent& c,
                                            const LocalSpellDefinition& parent,const LocalProcDefinition* branch=nullptr) {
    const auto& proc=branch?*branch:parent.proc;
    if(parent.stormstrikeProfile==4&&proc.effect==LocalProcEffect::RestoreMana)
        return localBaseMana(caster)*20/100;
    // Percent-max-health heals retain the reviewed percent, not a health
    // snapshot or spell-power/talent-scaled flat amount.
    if(proc.effect==LocalProcEffect::Ignite||proc.effect==LocalProcEffect::HealOwnerPctMaxHealth||proc.effect==LocalProcEffect::ApplyOwnerAura||proc.effect==LocalProcEffect::ConsumeOwnerAuraCharge||proc.effect==LocalProcEffect::ConsumeSpellCostCharge)return proc.amount;
    LocalSpellDefinition leaf;leaf.id=proc.spellId;leaf.spellFamily=proc.spellFamily;leaf.spellFamilyFlags=proc.spellFamilyFlags;
    // Earth Shield's scripted healing calculation uses its parent spell for
    // healing bonuses; the emitted event still identifies actual child 379.
    if(proc.effect==LocalProcEffect::HealOwner){leaf.id=parent.id;leaf.spellFamily=parent.spellFamily;leaf.spellFamilyFlags=parent.spellFamilyFlags;}
    uint32_t amount=localProcAmount(caster,proc);
    amount=uint32_t(localSpellAmountModifier(caster,c,leaf,float(amount),3));
    if(proc.effect==LocalProcEffect::DamageAttacker||proc.effect==LocalProcEffect::MeleeDamageShield||proc.effect==LocalProcEffect::HealOwner)
        amount=localSpellAmountAfterTalents(caster,c,leaf,amount,false);
    return amount;
}
// Pre-Save23 auras never carried talent-adjusted proc amounts. Retain their
// unmodified base instead of retroactively applying newly learned bonuses.
inline void hydrateLegacyLocalProcAmount(LocalStatAura& aura,const LocalRealmPlayer& recipient,const LocalSpellDefinition& d) {
    if(d.proc.effect==LocalProcEffect::None){aura.procAmountSnapshot=0;aura.hasProcAmountSnapshot=false;}
    else if(!aura.hasProcAmountSnapshot) {
        aura.procAmountSnapshot=localProcAmount(recipient,d.proc);aura.hasProcAmountSnapshot=true;
    }
}

// The reviewed reactive elemental shields share one exclusive aura group.
// Charges alone are not an exclusivity rule (other future charged auras may coexist).
inline bool localElementalShield(const LocalSpellDefinition& d) {
    return d.spellFamily==11 && d.proc.charges &&
        ((d.proc.effect==LocalProcEffect::DamageAttacker&&(d.spellFamilyFlags[0]&0x400)) ||
         (d.proc.effect==LocalProcEffect::RestoreMana&&(d.spellFamilyFlags[1]&0x20)) ||
         (localEarthShield(d)&&(d.spellFamilyFlags[1]&0x400)));
}
inline void normalizeLocalElementalShields(LocalRealmPlayer& p,const LocalWorldContent& c) {
    size_t keep=p.statAuras.size();uint32_t cooldown=0;
    for(size_t i=0;i<p.statAuras.size();++i) {
        const auto& a=p.statAuras[i];const auto* d=c.spell(a.spellId);
        if(!a.remainingMs||!d||!localElementalShield(*d))continue;
        cooldown=std::max(cooldown,a.procCooldownMs);
        // Old saves have no application order: retain longest remaining duration,
        // with stable vector order as a tie breaker.
        if(keep==p.statAuras.size()||a.remainingMs>p.statAuras[keep].remainingMs)keep=i;
    }
    if(keep==p.statAuras.size())return;
    for(size_t i=0;i<p.statAuras.size();++i)if(i!=keep) {
        const auto* d=c.spell(p.statAuras[i].spellId);
        if(d&&localElementalShield(*d))p.statAuras[i].remainingMs=0;
    }
    p.statAuras[keep].procCooldownMs=std::min(cooldown,c.spell(p.statAuras[keep].spellId)->proc.cooldownMs);
    std::erase_if(p.statAuras,[](const auto& a){return !a.remainingMs;});
}
// Legacy saves do not record application order. Keep one valid mage armor by
// remaining duration, then stable vector order, without granting fresh time.
inline void normalizeLocalMageArmors(LocalRealmPlayer& p,const LocalWorldContent& c) {
    size_t keep=p.statAuras.size();
    for(size_t i=0;i<p.statAuras.size();++i) {
        auto& a=p.statAuras[i];const auto* d=c.spell(a.spellId);
        if(!a.remainingMs||!d||!d->mageArmorGroup)continue;
        if(p.classId!=8||!d->unsupportedReason.empty()||!validLocalProc(*d)||
           a.mapId!=p.mapId||a.instanceId!=p.instanceId||(a.casterGuid&&a.casterGuid!=p.guid)) {
            a.remainingMs=0;continue;
        }
        a.casterGuid=p.guid;a.remainingMs=std::min(a.remainingMs,d->durationMs);
        if(!a.remainingMs)continue;
        if(keep==p.statAuras.size()||a.remainingMs>p.statAuras[keep].remainingMs)keep=i;
    }
    for(size_t i=0;i<p.statAuras.size();++i)if(i!=keep) {
        const auto* d=c.spell(p.statAuras[i].spellId);
        if(d&&d->mageArmorGroup)p.statAuras[i].remainingMs=0;
    }
    std::erase_if(p.statAuras,[](const auto& a){return !a.remainingMs;});
}
// the implementation (P04 competing auras). A save written before the rank chains were
// filled from spell_ranks can hold two ranks of one chain, or two auras a
// specific now makes exclusive, on one character. Keep one per conflict, the
// way Aura::CanStackWith would have: the higher rank stays; between two
// entries no rank orders, the longer remaining duration, then stable vector
// order. Nothing is granted fresh time. The elemental-shield and mage-armour
// normalisers above run first and carry their cooldown; this one is a no-op
// on what they already settled.
inline void normalizeLocalCompetingAuras(LocalRealmPlayer& p,const LocalWorldContent& c) {
    for(size_t i=0;i<p.statAuras.size();++i) {
        auto& a=p.statAuras[i];const auto* da=c.spell(a.spellId);
        if(!a.remainingMs||!da)continue;
        const auto casterA=a.casterGuid?a.casterGuid:p.guid;
        for(size_t j=i+1;j<p.statAuras.size()&&a.remainingMs;++j) {
            auto& b=p.statAuras[j];const auto* db=c.spell(b.spellId);
            if(!b.remainingMs||!db)continue;
            const auto casterB=b.casterGuid?b.casterGuid:p.guid;
            if(localAuraCanStackWith(c,*db,casterB,*da,casterA)&&localAuraCanStackWith(c,*da,casterA,*db,casterB))continue;
            bool dropA;
            if(laterSpellRank(c,a.spellId,b.spellId))dropA=true;
            else if(laterSpellRank(c,b.spellId,a.spellId))dropA=false;
            else dropA=a.remainingMs<b.remainingMs;
            (dropA?a:b).remainingMs=0;
        }
    }
    std::erase_if(p.statAuras,[](const auto& a){return !a.remainingMs;});
}
// the reference. The spellbook side of the same change: training erases every lower
// rank (Player::_addSpell marks the previous rank inactive and the trainer
// never offers it again), so a spellbook that holds several ranks of one
// chain - written when the chain was unlinked - keeps the highest known rank
// only. The trainer offers exactly that rank's successor afterwards.
inline size_t normalizeLocalKnownRanks(LocalRealmPlayer& p,const LocalWorldContent& c) {
    const auto known=p.knownSpells;
    const auto before=p.knownSpells.size();
    std::erase_if(p.knownSpells,[&](uint32_t id) {
        return std::any_of(known.begin(),known.end(),[&](uint32_t other){return other!=id&&laterSpellRank(c,id,other);});
    });
    return before-p.knownSpells.size();
}

}
