#!/usr/bin/env python3
"""Emit the reference's three stacking tables as bounded generated headers.

the implementation (P04, competing auras). AzerothCore reads rank identity from
`spell_ranks` (SpellMgr::LoadSpellRanks, SpellMgr.cpp:1279-1388) and group
exclusivity from `spell_group` / `spell_group_stack_rules`
(SpellMgr::LoadSpellGroups / LoadSpellGroupStackRules, :1700-1933). This
repository's importer used to know rank identity only through the client's own
SkillLineAbility.SupercededBySpell column, which is populated on 1,059 of
10,219 rows (docs/CURRENT_IMPLEMENTATION.md section 7.3). The
three files are emitted verbatim, validated the way the loaders validate them,
and consumed by include/game/local_spell_ranks.hpp.

    spell_ranks            -> local_spell_ranks_generated.inc              {first, id, rank}
    spell_group            -> local_spell_groups_generated.inc             {group, spell_or_negative_subgroup}
    spell_group_stack_rules-> local_spell_group_stack_rules_generated.inc  {group, rule}

Raw SQL stays outside the clean deliverable; only these rows and their hashes ship.
"""
import argparse, hashlib, json
from pathlib import Path
from import_azerothcore import sql_rows
PIN='9c416aaacb5537636abb13c80f55a88947838e33'

def generate(source, output, report):
    notice='// AzerothCore '+PIN+' data/sql/base/db_world/%s; generated by import_spell_stacking_tables.py.\n'
    # spell_ranks: chains of >= 2 with contiguous ranks 1..n (LoadSpellRanks drops
    # anything else with an error; at the pin nothing is dropped).
    ranks=sorted(sql_rows(source/'spell_ranks.sql','spell_ranks'),key=lambda r:(r['first_spell_id'],r['rank']))
    chains={}
    for r in ranks:
        chains.setdefault(r['first_spell_id'],[]).append((r['spell_id'],r['rank']))
    ids=set()
    for first,members in chains.items():
        if len(members)<2:raise ValueError('spell_ranks chain %d has one member'%first)
        if [m[1] for m in members]!=list(range(1,len(members)+1)):raise ValueError('spell_ranks chain %d is not contiguous'%first)
        if members[0][0]!=first:raise ValueError('spell_ranks chain %d does not start with itself'%first)
        for spell,_ in members:
            if spell in ids:raise ValueError('spell_ranks spell %d listed twice'%spell)
            ids.add(spell)
    (output/'local_spell_ranks_generated.inc').write_text(notice%'spell_ranks.sql'+''.join('{%d,%d,%d},\n'%(r['first_spell_id'],r['spell_id'],r['rank']) for r in ranks))
    # spell_group: (id, spell_id); negative spell_id references another group.
    groups=sorted(sql_rows(source/'spell_group.sql','spell_group'),key=lambda r:(r['id'],r['spell_id']))
    group_ids={r['id'] for r in groups}
    for r in groups:
        if r['id']<=0 or r['id']>65535:raise ValueError('spell_group id out of range')
        if r['spell_id']<0 and -r['spell_id'] not in group_ids:raise ValueError('spell_group %d references missing sub-group %d'%(r['id'],-r['spell_id']))
        if r['spell_id']==0:raise ValueError('spell_group %d lists spell 0'%r['id'])
    (output/'local_spell_groups_generated.inc').write_text(notice%'spell_group.sql'+''.join('{%d,%d},\n'%(r['id'],r['spell_id']) for r in groups))
    rules=sorted(sql_rows(source/'spell_group_stack_rules.sql','spell_group_stack_rules'),key=lambda r:r['group_id'])
    seen=set()
    for r in rules:
        if r['group_id'] not in group_ids:raise ValueError('stack rule for missing group %d'%r['group_id'])
        if r['stack_rule'] not in (0,1,2,3,4):raise ValueError('unknown stack rule %d'%r['stack_rule'])
        if r['group_id'] in seen:raise ValueError('duplicate stack rule for group %d'%r['group_id'])
        seen.add(r['group_id'])
    (output/'local_spell_group_stack_rules_generated.inc').write_text(notice%'spell_group_stack_rules.sql'+''.join('{%d,%d},\n'%(r['group_id'],r['stack_rule']) for r in rules))
    info={'source_commit':PIN,
          'inputs':{n:hashlib.sha256((source/n).read_bytes()).hexdigest() for n in ('spell_ranks.sql','spell_group.sql','spell_group_stack_rules.sql')},
          'spell_ranks_rows':len(ranks),'spell_ranks_chains':len(chains),
          'spell_group_rows':len(groups),'spell_group_groups':len(group_ids),'spell_group_subgroup_rows':sum(1 for r in groups if r['spell_id']<0),
          'spell_group_stack_rules_rows':len(rules),'stack_rule_histogram':{str(k):sum(1 for r in rules if r['stack_rule']==k) for k in range(5)},
          'outputs':{n:hashlib.sha256((output/n).read_bytes()).hexdigest() for n in ('local_spell_ranks_generated.inc','local_spell_groups_generated.inc','local_spell_group_stack_rules_generated.inc')},
          'scope':'Generated metadata, not gameplay/console acceptance'}
    report.write_text(json.dumps(info,indent=2)+'\n');print(json.dumps(info))
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('source',type=Path,help='directory holding the three pinned SQL dumps')
    p.add_argument('output',type=Path);p.add_argument('report',type=Path);a=p.parse_args();generate(a.source,a.output,a.report)
