#!/usr/bin/env python3
"""Build compact merchant tables from the pinned world database; no SQL runtime.

The item_template input is already preserved in world_source_sql.tar.gz.
npc_vendor and conditions are preserved in vendor_source_sql.tar.gz. Extended
currencies and scripted vendor conditions are not converted into unrestricted
gold offers. Item reputation gates are retained as explicit runtime requirements;
every remaining omission is recorded in the report.
"""
from __future__ import annotations

import argparse
import collections
import hashlib
import json
from pathlib import Path

from import_azerothcore import PINNED_COMMIT, REPOSITORY, sql_rows


def compile_vendor_catalog(source: Path, output: Path, report_path: Path):
    tables = ("npc_vendor", "item_template", "conditions")
    hashes = {name: hashlib.sha256((source / f"{name}.sql").read_bytes()).hexdigest()
              for name in tables}
    rows = list(sql_rows(source / "npc_vendor.sql", "npc_vendor"))
    items = {row["entry"]: row for row in sql_rows(source / "item_template.sql", "item_template")}
    # CONDITION_SOURCE_TYPE_NPC_VENDOR is 23 in this pinned core. References
    # and ElseGroup branches are conservatively retained as a purchase gate.
    conditional = {(r["sourcegroup"], r["sourceentry"])
                   for r in sql_rows(source / "conditions.sql", "conditions")
                   if r["sourcetypeorreferenceid"] == 23}
    by_vendor = collections.defaultdict(list)
    for row in rows:
        by_vendor[row["entry"]].append(row)

    def expand(entry, chain=()):
        if entry in chain or len(chain) >= 16:
            raise ValueError(f"Cyclic or excessive npc_vendor reference: {chain}/{entry}")
        for row in sorted(by_vendor[entry], key=lambda r: (r["slot"], r["item"], r["extendedcost"])):
            if row["item"] < 0:
                if -row["item"] not in by_vendor:
                    raise ValueError(f"Missing npc_vendor reference: {row}")
                yield from expand(-row["item"], chain + (entry,))
            else:
                yield row

    offers, prices, excluded = [], {}, []
    for entry in sorted(by_vendor):
        seen = set()
        for row in expand(entry):
            item_id = row["item"]
            item = items.get(item_id)
            reason = None
            if not item:
                reason = "missing item_template"
            elif row["extendedcost"]:
                reason = "extended currency not implemented"
            elif (entry, item_id) in conditional or (row["entry"], item_id) in conditional:
                reason = "vendor condition requires authority condition engine"
            elif row["maxcount"] and not row["incrtime"]:
                reason = "limited stock has invalid restock interval"
            if reason:
                excluded.append({"entry": entry, "item": item_id,
                                 "extendedCost": row["extendedcost"], "reason": reason})
                continue
            if item_id in seen:
                continue
            seen.add(item_id)
            offers.append((entry, item_id, row["maxcount"], row["incrtime"],
                           item["requiredreputationfaction"],
                           item["requiredreputationrank"] if item["requiredreputationfaction"] else 0))
            prices[item_id] = (item_id, max(0, item["buyprice"]), max(1, item["buycount"]),
                               max(0, item["sellprice"]))

    output.mkdir(parents=True, exist_ok=True)
    note = (f"// Generated by tools/local_realm/import_vendor_catalog.py\n"
            f"// AzerothCore {PINNED_COMMIT}; GPL-2.0, see assets/local_realm/NOTICE.txt.\n")
    (output / "local_vendor_stock_generated.inc").write_text(
        note + "".join("{%du,%du,%du,%du,%du,%du},\n" % row for row in offers))
    (output / "local_vendor_prices_generated.inc").write_text(
        note + "".join("{%du,%du,%du,%du},\n" % prices[key] for key in sorted(prices)))
    report = {
        "sourceCommit": PINNED_COMMIT, "repository": REPOSITORY,
        "sourceHashes": hashes, "sourceRows": len(rows),
        "sourceVendors": len(by_vendor), "runtimeOffers": len(offers),
        "runtimeVendors": len({row[0] for row in offers}), "runtimePriceRows": len(prices),
        "maximumVendorOffers": max(collections.Counter(row[0] for row in offers).values()),
        "runtimeStaticBytes": len(offers) * 24 + len(prices) * 16,
        "excludedReasons": dict(collections.Counter(row["reason"] for row in excluded)),
        "excludedOffers": excluded,
        "limits": [
            "Base SQL snapshot only, no subsequent update scripts.",
            "Required item reputation is retained and enforced by the local realm.",
            "Scripted vendor conditions remain excluded until their condition engine is modeled.",
            "Extended-cost currency offers are excluded, never sold for gold instead.",
            "Base BuyPrice and BuyCount retained; Friendly/Honored/Revered/Exalted discounts are applied at runtime.",
            "Limited stock is shared per NPC spawn during the current realm session; restart replenishes it.",
        ],
    }
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps({k: v for k, v in report.items()
                      if k not in ("excludedOffers", "sourceHashes", "limits")}, indent=2))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sql-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()
    compile_vendor_catalog(args.sql_dir, args.output_dir, args.report)
