#!/usr/bin/env python3
"""Generate compact auction metadata from the pinned server SQL base dump.

The market rules are local gameplay rules; the item fields and drop membership
come from the same source as the installed world catalog. No SQL runtime or
walking playerbots are needed by the resulting auction board.
"""
import argparse
import hashlib
import json
from pathlib import Path
from import_azerothcore import sql_rows, PINNED_COMMIT, REPOSITORY

# TCG items that exist in the 3.3.5a source. Resolve their *tradeable* variants
# from authoritative item names, rather than supplying guessed numeric IDs.
# Names/source: https://www.wowhead.com/guide/vanity-collections/obtaining-trading-card-loot
TCG_NAMES = {
    'Riding Turtle', 'Reins of the Spectral Tiger', 'Reins of the Swift Spectral Tiger',
    'X-51 Nether-Rocket', 'X-51 Nether-Rocket X-TREME', 'Big Battle Bear',
    'Magic Rooster Egg', 'Wooly White Rhino',
}

def generate(source, output, report):
    paths = [source / 'item_template.sql', source / 'creature_loot_template.sql',
             source / 'reference_loot_template.sql']
    drops, drop_chance = set(), {}
    for path in paths[1:]:
        for row in sql_rows(path, path.stem):
            if row['item'] > 0:
                drops.add(row['item'])
            if (path.stem == 'creature_loot_template' and not row['reference'] and
                not row['groupid'] and not row['questrequired'] and row['lootmode'] & 1 and
                0 < row['chance'] <= 100):
                chance = max(1,min(10000,round(row['chance']*100)))
                drop_chance[row['item']] = max(drop_chance.get(row['item'],0),chance)
    lines, mounts = [], []
    for row in sorted(sql_rows(paths[0], 'item_template'), key=lambda r: r['entry']):
        cls, sub, quality, binding = (row[k] for k in ('class', 'subclass', 'quality', 'bonding'))
        material = cls == 7
        mount = cls == 15 and sub == 5
        tcg = mount and binding == 0 and row['name'] in TCG_NAMES
        drop = mount and row['entry'] in drops
        tradeable = binding not in (1, 4) and cls != 12 and quality < 7
        supply = (tradeable and 1 <= quality <= 4 and (row['sellprice'] > 0 or material)
                  and cls in (0, 1, 2, 3, 4, 7, 9, 16)) or tcg or drop
        flags = int(material) | (int(mount) << 1) | (int(drop) << 2) | (int(tcg) << 3) | (int(supply) << 4)
        values = [row['entry'], max(0,row['sellprice']), max(0,row['buyprice']),
                  row['allowableclass'] & 0xffffffff, row['allowablerace'] & 0xffffffff,
                  next((row['spellid_'+str(n)] for n in range(1,6) if mount and row['spelltrigger_'+str(n)] == 6 and row['spellid_'+str(n)] > 0), 0),
                  max(1,min(1000,row['stackable'] or 1)), drop_chance.get(row['entry'],0), cls, sub, quality,
                  row['requiredlevel'], binding, flags]
        lines.append('{' + ','.join(str(v)+'u' for v in values) + '},')
        if mount and supply:
            mounts.append({'id':row['entry'],'name':row['name'],'drop':drop,'tcg':tcg})
    output.write_text('// Generated by import_auction_catalog.py; AzerothCore '+PINNED_COMMIT+'\n'
                      '// Item/drop data: '+REPOSITORY+' (GPL-2.0, see assets/local_realm/NOTICE.txt).\n'
                      + '\n'.join(lines)+'\n')
    report.write_text(json.dumps({'repository':REPOSITORY,'commit':PINNED_COMMIT,'rows':len(lines),
        'sourceHashes':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in paths},
        'dropProbabilityPolicy':'Highest known positive ungrouped nonquest normal creature-loot chance; unknown/grouped/reference-only rates carry no probability premium',
        'marketMounts':mounts},indent=2)+'\n')
    print('Auction metadata:',len(lines),'items;',len(mounts),'documented market mounts')

if __name__ == '__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('source',type=Path)
    parser.add_argument('output',type=Path)
    parser.add_argument('report',type=Path)
    args=parser.parse_args()
    generate(args.source,args.output,args.report)
