#!/usr/bin/env python3
"""Generate zone/team graveyard links from pinned AzerothCore SQL.
Coordinates are joined separately from pinned game_graveyard; this contains links only.
"""
from pathlib import Path
import collections, hashlib, json
from import_azerothcore import sql_rows, PINNED_COMMIT, REPOSITORY
root=Path(__file__).resolve().parents[2]
source=Path(__file__).with_name('graveyard_zone_source.sql')
rows=sorted(sql_rows(source,'graveyard_zone'),key=lambda r:(r['id'],r['ghostzone']))
assert len({(r['id'],r['ghostzone']) for r in rows})==len(rows)
assert all(r['id']>0 and r['ghostzone']>0 and r['faction'] in (0,67,469) for r in rows)
lines=['#pragma once','#include <array>','#include <cstdint>','', 'namespace wowee::game {',
'// Generated by tools/local_realm/import_graveyard_links.py; pinned AC '+PINNED_COMMIT,
'// Keep zone/team links: one safe-location may have different faction rules per zone.',
'// Coordinates are joined from pinned game_graveyard.sql, not synthesized.',
'struct LocalGraveyardLink { uint32_t id, zoneId, team; };',
'inline constexpr std::array<LocalGraveyardLink, '+str(len(rows))+'> kLocalGraveyardLinks{{']
lines += ['    {'+str(r['id'])+'u, '+str(r['ghostzone'])+'u, '+str(r['faction'])+'u},' for r in rows]
lines += ['}};', '} // namespace wowee::game','']
(root/'include/game/local_graveyard_links.hpp').write_text('\n'.join(lines))
report={'upstream':REPOSITORY,'commit':PINNED_COMMIT,'sourceURL':REPOSITORY+'/blob/'+PINNED_COMMIT+'/data/sql/base/db_world/graveyard_zone.sql','sourceSHA256':hashlib.sha256(source.read_bytes()).hexdigest(),'table':'graveyard_zone','sourceRows':len(rows),'outputRows':len(rows),'uniqueSafeLocationIds':len(set(r['id'] for r in rows)),'teamCounts':dict(collections.Counter(r['faction'] for r in rows)),'coordinateSource':'Pinned game_graveyard.sql via local_graveyard_sites.hpp; only referenced IDs eligible','teamSemantics':{'0':'neutral','67':'Horde','469':'Alliance'},'eligibility':'Per graveyard ID and GhostZone; never merge faction masks across different zones'}
(root/'assets/local_realm/graveyard_links.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps(report,indent=2))
