#!/usr/bin/env python3
"""Emit the reference's spell_threat table and its trainer offer set as bounded generated headers.

the implementation (P05, shared combat rules). AzerothCore reads a spell's flat, percent
and attack-power threat terms from `spell_threat` (SpellMgr::LoadSpellThreats,
consumed by Spell::HandleThreatSpells, Spell.cpp:5759-5811, and
ThreatManager::CalculateModifiedThreat, ThreatManager.cpp:708-735) and builds
a player's spellbook from `trainer_spell` (never from the client's
SkillLineAbility.dbc). This repository's importer had neither: no cast added
its table threat, and four proc copies with a stray class mask in
SkillLineAbility (Lightning Overload's 49239/49240/49268/49269) were offered
as trainable (docs/CURRENT_IMPLEMENTATION.md sections 3.3 and 7).
Both files are emitted verbatim and consumed by
include/game/local_spell_threat.hpp and include/game/local_trainer_spells.hpp.

    spell_threat  -> local_spell_threat_generated.inc    {entry, flatMod, pctMod, apPctMod}
    trainer_spell -> local_trainer_spells_generated.inc  distinct SpellId, ascending

Raw SQL stays outside the clean deliverable; only these rows and their hashes ship.
"""
import argparse, hashlib, json
from pathlib import Path
from import_azerothcore import sql_rows
PIN='9c416aaacb5537636abb13c80f55a88947838e33'

def cfloat(v):
    """A float literal that round-trips the dump's decimal text exactly."""
    return repr(float(v))+'f'

def generate(source, output, report):
    notice='// AzerothCore '+PIN+' data/sql/base/db_world/%s; generated by import_spell_threat_tables.py.\n'
    # spell_threat(entry, flatMod, pctMod, apPctMod): LoadSpellThreats keeps a
    # row only for a spell that exists (SpellMgr.cpp); every row at the pin does.
    threat=sorted(sql_rows(source/'spell_threat.sql','spell_threat'),key=lambda r:r['entry'])
    seen=set()
    for r in threat:
        if r['entry']<=0:raise ValueError('spell_threat entry out of range')
        if r['entry'] in seen:raise ValueError('spell_threat entry %d listed twice'%r['entry'])
        if r['flatmod'] is None:raise ValueError('spell_threat entry %d has a NULL flatMod'%r['entry'])
        if not (0<=float(r['pctmod'])<=100) or not (0<=float(r['appctmod'])<=100):raise ValueError('spell_threat entry %d modifier out of range'%r['entry'])
        seen.add(r['entry'])
    (output/'local_spell_threat_generated.inc').write_text(notice%'spell_threat.sql'+''.join(
        '{%d,%d,%s,%s},\n'%(r['entry'],r['flatmod'],cfloat(r['pctmod']),cfloat(r['appctmod'])) for r in threat))
    # trainer_spell(TrainerId, SpellId, ...): the distinct spells any trainer
    # offers. Only membership is read here.
    trainer=sorted({r['spellid'] for r in sql_rows(source/'trainer_spell.sql','trainer_spell')})
    for spell in trainer:
        if spell<=0:raise ValueError('trainer_spell SpellId out of range')
    (output/'local_trainer_spells_generated.inc').write_text(notice%'trainer_spell.sql'+''.join('%d,\n'%s for s in trainer))
    info={'source_commit':PIN,
          'inputs':{n:hashlib.sha256((source/n).read_bytes()).hexdigest() for n in ('spell_threat.sql','trainer_spell.sql')},
          'spell_threat_rows':len(threat),
          'spell_threat_flat_rows':sum(1 for r in threat if r['flatmod']),
          'spell_threat_pct_rows':sum(1 for r in threat if float(r['pctmod'])!=1.0),
          'spell_threat_ap_rows':sum(1 for r in threat if float(r['appctmod'])!=0.0),
          'trainer_spell_rows':len(trainer),
          'outputs':{n:hashlib.sha256((output/n).read_bytes()).hexdigest() for n in ('local_spell_threat_generated.inc','local_trainer_spells_generated.inc')},
          'scope':'Generated metadata, not gameplay/console acceptance'}
    report.write_text(json.dumps(info,indent=2)+'\n');print(json.dumps(info))
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('source',type=Path,help='directory holding the two pinned SQL dumps')
    p.add_argument('output',type=Path);p.add_argument('report',type=Path);a=p.parse_args();generate(a.source,a.output,a.report)
