#!/usr/bin/env python3
"""Compile the shaman weapon imbues: what each rank's temporary enchant does.

A weapon imbue is a Shaman (SpellFamily 11) SPELL_EFFECT_ENCHANT_ITEM_TEMPORARY
(54) whose MiscValue names a SpellItemEnchantment row (3.3.5a build 12340).
Only these enchant shapes are compiled:

  rockbiter    ITEM_ENCHANTMENT_TYPE_TOTEM (6): Player::ApplyEnchantment adds
               amount x the weapon's speed in seconds to the main-hand damage.
               The player's ranks carry no enchant: Spell::EffectEnchantItemTmp
               picks one (36744...) by the effect's damage per second, which is
               that enchant's amount, so the effect value itself is compiled;
  flametongue  EQUIP_SPELL (3) of a Flametongue Weapon (Passive) rank, whose
               effect 0 base points spell_sha_flametongue_weapon turns into
               10444's fire damage on each main-hand hit;
  windfury     EQUIP_SPELL (3) of Windfury Weapon (Passive): the enchant amount
               is the proc chance, spell_sha_windfury_weapon the two extra
               attacks (25504) with 8232's effect 1 x the weapon speed;
  frostbrand   COMBAT_SPELL (1) of a Frostbrand Attack rank (its slow and frost
               hit), at spell_enchant_proc_data's 9 procs per minute.

    python3 -B tools/local_realm/import_weapon_imbues.py <DBFilesClient dir> \\
        --output include/game/local_weapon_imbues_generated.inc
"""
from __future__ import annotations
import argparse, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from import_consumables import dbc

KINDS = {'Rockbiter Weapon': 1, 'Flametongue Weapon': 2, 'Windfury Weapon': 3, 'Frostbrand Weapon': 4}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('dbc_dir', type=Path)
    ap.add_argument('--output', type=Path, required=True)
    args = ap.parse_args()
    spells, text = dbc(args.dbc_dir / 'Spell.dbc')
    enchants, _ = dbc(args.dbc_dir / 'SpellItemEnchantment.dbc')
    rows = []
    for sid, (u, i) in sorted(spells.items()):
        kind = KINDS.get(text(u[136]))
        if not kind or u[208] != 11:
            continue
        effect = next((e for e in range(3) if u[71 + e] == 54), None)
        if effect is None or u[71 + (effect + 1) % 3] == 54:
            continue
        if kind == 1 and not u[110 + effect] and (u[209] & 0x400000) and 0 < i[80 + effect] + 1 <= 1000:
            ru, ri = spells[36744]  # rank 1's enchanting spell: its duration
            rows.append((sid, kind, i[80 + effect] + 1, 0, 0, ri[80] + 1))
            continue
        enchant = enchants.get(u[110 + effect])
        if not enchant:
            continue
        eu, _ = enchant
        etype, amount, espell = eu[2], eu[5], eu[11]
        duration = i[80 + effect] + 1  # CalcValue: base + 1, in seconds
        if any(eu[2 + k] for k in (1, 2)) or duration <= 0 or duration > 3600:
            continue
        if kind == 1 and etype == 6 and 0 < amount <= 1000:
            rows.append((sid, kind, amount, 0, 0, duration))
        elif kind == 2 and etype == 3 and espell in spells:
            pu, pi = spells[espell]
            if pu[71] == 6 and pu[95] == 4 and pi[80] >= 0:
                rows.append((sid, kind, pi[80] + 1, espell, 0, duration))
        elif kind == 3 and etype == 3 and espell in spells and 0 < amount <= 100:
            wu, wi = spells[8232]  # spell_sha_windfury_weapon reads rank 1's effect 1
            rows.append((sid, kind, amount, espell, wi[81] + (1 if wu[75] else 0), duration))
        elif kind == 4 and etype == 1 and espell in spells:
            rows.append((sid, kind, 9, espell, 0, duration))
    with open(args.output, 'w') as out:
        out.write('// Generated by tools/local_realm/import_weapon_imbues.py from Spell.dbc and\n'
                  '// SpellItemEnchantment.dbc: {spell, kind, amount, spell it uses, bonus, seconds}.\n')
        for r in rows:
            out.write('{%d,%d,%d,%d,%d,%d},\n' % r)
    print(f'{len(rows)} imbue ranks -> {args.output}')


if __name__ == '__main__':
    main()
