#!/usr/bin/env python3
"""Emit source equipment spell power for complete Fire/Frost Ward scaling."""
import argparse,hashlib,json
from pathlib import Path
from import_azerothcore import sql_rows
PIN='9c416aaacb5537636abb13c80f55a88947838e33'
def generate(source,output,report):
    values=[]
    for row in sql_rows(source,'item_template'):
        if row['class'] not in (2,4):continue
        amount=sum(row['stat_value'+str(i)] for i in range(1,11) if row['stat_type'+str(i)] in (42,45))
        if not amount:continue
        if abs(amount)>1000000:raise ValueError(row['entry'])
        values.append((row['entry'],amount))
    output.write_text('// AzerothCore '+PIN+' item_template stat42/45; generated by import_ward_spell_power_catalog.py.\n'+''.join('{%d,%d},\n'%v for v in sorted(values)))
    report.write_text(json.dumps({'source_commit':PIN,'input_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'items':len(values),'output_sha256':hashlib.sha256(output.read_bytes()).hexdigest()},indent=2)+'\n')
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('source',type=Path);p.add_argument('output',type=Path);p.add_argument('report',type=Path);a=p.parse_args();generate(a.source,a.output,a.report)
